title: Uploading your project to GitHub
tagline: Everything you need to know about uploading your project to GitHub
description: You’re an upload away from pushing your projects further with a full suite of development tools and premier third-party apps on GitHub. This course helps you seamlessly upload your code to GitHub and introduce you to exciting next steps to elevate your project.
template:
  name: github-upload
before:
  - type: createIssue
    title: Planning the upload to GitHub
    body: 01_make-a-plan.md
steps:
  - title: Plan the upload
    description: Explore your options for making the move to GitHub
    event: issues.closed
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/issues/1
    actions:
      - type: createIssue
        action_id: new_issue
        title: Preparing the project for Git
        body: 04_prepare.md
      - type: respond
        with: 02_next.md
        data:
          issueURL: '%actions.new_issue.data.html_url%'

  - title: Prepare the project
    description: Prepare your project for a happy life on GitHub
    event: push
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/issues
    actions:
      - type: getTree
        action_id: tree
      - type: gate
        left: '%actions.tree.data.tree%'
        operator: includes
        right: path:.gitignore
        else:
          type: respond
          issue: Preparing the project for Git
          with: e_needs_gitignore.md
      - type: createIssue
        title: Uploading your project
        body: 05_move-local.md
        action_id: new_issue
      - type: closeIssue
        issue: Preparing the project for Git
      - type: respond
        with: 02_next.md
        issue: Preparing the project for Git
        data:
          issueURL: '%actions.new_issue.data.html_url%'

  - title: Begin the upload
    description: Publish your project on GitHub
    event: push
    link: https://github.com/{{ user.username }}/{{ course.template.name }}
    actions:
      - type: createIssue
        action_id: new_issue
        title: Public or private repository?
        body: 07_confirm_visibility.md
      - type: closeIssue
        issue: Importing your project
      - type: respond
        with: 06_move-done-local.md
        issue: Importing your project
        data:
          url: '%actions.new_issue.data.html_url%'

  - title: Public or private repository?
    description: Understand the difference between a public and private repository
    event: issues.closed
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/issues
    actions:
      - type: createIssue
        action_id: new_issue
        title: A few parting words
        body: 08_graceful-exit.md
      - type: respond
        with: 02_next.md
        data:
          issueURL: '%actions.new_issue.data.html_url%'
tags:
  - Git
  - GitHub

order: 4
