title: Uploading your project to GitHub
tagline: Everything you need to know about uploading your project to GitHub
description: You’re an upload away from using a full suite of development tools and premier third-party apps on GitHub. This course helps you seamlessly upload your code to GitHub and introduces you to exciting next steps to elevate your project.
template:
  name: github-upload
  repo: false
tags:
  - Git
  - GitHub
before:
  - type: createIssue
    title: Planning the upload to GitHub
    body: 00_make-a-plan.md
    store:
      first_issue_url: '{{ result.data.html_url }}'
    
steps:
  #1
  - title: Plan the upload
    description: Explore your options for making the move to GitHub.
    event: issues.closed
    link: '{{ store.first_issue_url }}'
    actions:
      - type: createIssue
        action_id: new_issue
        title: Preparing the project for Git
        body: 01_prepare.md
        store: 
          second_issue_url: '{{ result.data.html_url }}'
      - type: respond
        with: 01_next.md
        data:
          issueURL: '{{ store.second_issue_url }}'

  #2
  - title: Prepare the project
    description: Prepare your project for a happy life on GitHub.
    event: issues.closed
    link: '{{ store.second_issue_url }}'
    actions:
      - type: createIssue
        title: Uploading your project
        body: 02_move-local.md
        store: 
          third_issue_url: '{{ results.data.html_url }}'
        action_id: new_issue
      - type: respond
        with: 01_next.md
        data:
          issueURL: '{{ store.third_issue_url }}'

  #3
  - title: Begin the upload
    description: Publish your project on GitHub.
    event: push
    link: '{{ store.third_issue_url }}'
    actions:
      - type: getTree
        action_id: tree
      - type: gate
        required: false
        left: '%actions.tree.data.tree%'
        operator: includes
        right: path:.gitignore
        else:
          type: respond
          issue: Uploading your project
          with: e_needs_gitignore.md
      - type: createIssue
        action_id: new_issue
        title: Public or private repository?
        body: 03_confirm-visibility.md
        store:
          fourth_issue_url: {{ results.data.html_url }}
        data:
          private: '%payload.repository.private%'
      - type: closeIssue
        issue: Uploading your project
      - type: respond
        with: 03_move-done-local.md
        issue: Uploading your project
        data:
          issueURL: '{{ store.fourth_issue_url }}'
  #4
  - title: Public or private repository?
    description: Understand the difference between a public and private repository.
    event: issues.closed
    link: '{{ store.fourth_issue_url }}'
    actions:
      - type: createIssue
        action_id: new_issue
        title: A few parting words
        body: 04_graceful-exit.md
        store:
          fifth_issue_url: {{ results.data.html_url }}
      - type: respond
        with: 01_next.md
        data:
          issueURL: '{{ store.fifth_issue_url }}'
